# Config
# ========================================================================================
url:                   https://sseunng.github.io
baseurl:               ''
lang:                  ko-KR

# The title of your blog. Used in the sidebar and the browser tab.
title:                 1st Birthday

# A short description (~150 chars) of the page used for the meta description tag.
# Can use markdown, but no more than one paragraph (enforced by `>`)

# Build settings
markdown: kramdown
